version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      include: scope
    groups:
      gradle-all:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    groups:
      actions-all:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci/cd
